### ISSUE TITLE
SagePay REGISTERED response should not be flagged as failed payment.

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/Gold-Cart#10]
Referring to the [SagePay documentation](http://www.sagepay.co.uk/file/6941/download-document/FORM_Protocol_and_Integration_Guidelines_300114.pdf), if using SagPay with AUTHENTICATE rather than taking payment immediately...

> The AUTHENTICATE and AUTHORISE methods are specifically for use by merchants who are either (i) unable to fulfil the majority of orders in less than 6 days (or sometimes need to fulfil them after 30 days) or (ii) do not know the exact amount of the transaction at the time the order is placed (for example, items shipped priced by weight, or items affected by foreign exchange rates).

... if 3D secure services cannot be checked then the card details are still held by SagePay it will returned a REGISTERED response:

> Your site will register your transaction with a TxType of AUTHENTICATE, and redirect the customer to Sage Pay Server to enter their card details. Sage Pay Server will contact the 3D-Secure directories to check if the card is part of the scheme. If it is not, then the card details are simply held safely at Sage Pay and your SuccessURL is sent a Status of REGISTERED (This also happens if you do not have 3D-Secure active on your account or have used the Apply3DSecure flag to turn it off).

This means the card details have been retained and could be charged, it just wasn;t possible to 3D-secure check them, so the payment didn't fail as it can still be taken.

Also if you are authorising payments and someone pays with PayPal, the response will always be flagged as REGISTERED as 3D-secure checks cannot be does in PayPal.

> Additional notes for using Authenticate and Authorise with PayPal transactions.
> You can use the Authenticate and Authorise Payment Type but the transaction will only ever be REGISTERED (because the transaction will never be 3D Secured).

Currently PayPal payments are always flagged as failed even though payment is taken.

Submitting a pull request to fix this imminently.

**Comment by benhuson** [comment]
@JustinSainton For next release if possible? pretty please

**Comment by JustinSainton** [comment]
Done :+1:

**Comment by benhuson** [comment]
:smile:
