### ISSUE TITLE
eWay requires TLS1.2 from August 2017

### ISSUE THREAD

**Issue by galbaras** [wp-e-commerce/Gold-Cart#27]
From August 2017, eWay will be rolling out changes to the TLS (Transport Layer Security) infrastructure across the payment system. These changes will impact all browsers or systems that use TLS 1.0 or TLS 1.1. Any connection attempts made that are not using TLS 1.2 protocols will be rejected and you will not be able to access eWAY or our payment system.

What version of TLS does Gold Cart use for the eWay payment gateway connections?

If this is not related to the plugin code, what needs to be done to comply?

**Comment by mihaijoldis** [comment]
Hey there,
There are no changes needed to Gold Cart. Its more of a server related thing. 
You can install this plugin to test if you are ready: https://wordpress.org/plugins/tls-1-2-compatibility-test/
